# Generated by Xplorer, do not modify.
# This Makefile builds _single_build Debug

%:: RCS/%,v
%:: RCS/%
%:: s.%
%:: SCCS/s.%
.SUFFIXES:
.SUFFIXES: .a .o .c .cc .C .cpp .s .S .h


# There should not be an 'sh.exe' in path
export SHELL = cmd


# There should never be any unknown unix-like tools on the path
# In particular there should not be an 'sh.exe' in the system32 directory
export PATH = C:\xtensa\XtDevTools\install\tools\RI-2018.0-win32\XtensaTools\bin\;C:\xtensa\XtDevTools\install\tools\RI-2018.0-win32\XtensaTools\lib\iss\;C:\WINDOWS\system32

all:
	cmd /c "cd /D ""C:\\Users\\admin\\Desktop\\HIFI_Candence\\RTOS\\workspace\\RTOSDemo\\bin\\hifi5_lite_v5_0_fpga\\Debug"" && $(MAKE) all  "

clean:
	cmd /c "cd /D ""C:\\Users\\admin\\Desktop\\HIFI_Candence\\RTOS\\workspace\\RTOSDemo\\bin\\hifi5_lite_v5_0_fpga\\Debug"" && $(MAKE) clean  "
